//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UP_1.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Countries
    {
        public int Id_Countries { get; set; }
        public string Name_Countries { get; set; }
        public string Capital { get; set; }
        public Nullable<int> Square { get; set; }
        public Nullable<int> Naselenie { get; set; }
        public string Kontinent { get; set; }
    }
}
