//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UP_1.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ekzamen
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> Kod { get; set; }
        public Nullable<int> Id_students { get; set; }
        public Nullable<int> Id_Employee { get; set; }
        public string Audetoria { get; set; }
        public Nullable<int> Ocenka { get; set; }
    
        public virtual Disciplina Disciplina { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Students Students { get; set; }
    }
}
