//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UP_1.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.Ekzamen = new HashSet<Ekzamen>();
        }
    
        public int Id_Employee { get; set; }
        public Nullable<int> Abbreviatura_Employee { get; set; }
        public string FIO { get; set; }
        public string Post { get; set; }
        public Nullable<decimal> Oklad { get; set; }
        public Nullable<int> Shef { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ekzamen> Ekzamen { get; set; }
        public virtual Kafedra Kafedra { get; set; }
        public virtual Inshener Inshener { get; set; }
        public virtual Prepodovatel Prepodovatel { get; set; }
        public virtual Zav_kafedroy Zav_kafedroy { get; set; }
    }
}
